# Site
name: "Tech That Sticks"
title: "Tech That Sticks | 기술이 머물고, 뿌리내리는 이야기"
description: "기술 도입보다 정착에 집중하는 실무 중심 테크 블로그. 실제로 쓰이는 기술, 자동화, BI, 템플릿, 실전 사례와 인사이트."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: G-LFFKMBQP12  # GA4 Tracking ID 'G-LFFKMBQP12
disqus: 'ltnalsxl'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ltnalsxl:
    name: sumin  # 본인의 닉네임 또는 이름
    display_name: Sumin Lee  # 화면에 표시될 이름
    gravatar: e56154546cf4be74e393c62d1ae9f9d4  # Gravatar 해시 (원하는 경우만 수정)
    web: 
    twitter: 
    description: "Sumin"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Categories used to organize posts
categories:
  - log
  - project-lab
  - automation-studio
  - bi-implementation
  - templates
  - insights
  - notion
  - excel
  - google-sheets
  - power-bi
  - career-playbook
  - share-speak
  - business-insight
  - tech-trend
  - data-ecosystem
  - digital-transformation
  - worktech
  - conference
  - slides
  - talk-notes
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

nav:
  - title: "Log"
    url: "/categories/log/"
  - title: "Project Lab"
    url: "/categories/project-lab/"
    subcategories:
      - "Automation Studio"
      - "BI 도입기"
  - title: "Templates"
    url: "/categories/templates/"
  - title: "Insights"
    url: "/categories/insights/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"
