# Site
name: "SumInsideTech"
title: "SumInsideTech | Deep Tech Stories & Analytics"
description: "Looking inside tech products and trends. Sharing in-depth analysis and stories about digital innovations."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: G-LFFKMBQP12  # GA4 Tracking ID 'G-LFFKMBQP12
disqus: 'ltnalsxl'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ltnalsxl:
    name: sumin  # 본인의 닉네임 또는 이름
    display_name: Sumin Lee  # 화면에 표시될 이름
    gravatar: e56154546cf4be74e393c62d1ae9f9d4  # Gravatar 해시 (원하는 경우만 수정)
    web: 
    twitter: 
    description: "Sumin"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Categories 설정 (Tech Innovation → Tech Stories 변경 반영)
categories:
  - build-log
  - automation
  - tech-implementation
  - template-archive
  - career-mentoring
  - talk-teach
  - suminsidetech
  - data-insight
  - business-insight
  - change-management
  - workflow-optimization
  - data-engineering
  - bi
  - certification
  - ai
  - hardware
  - education
  - growth
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

nav:
  - title: "About"
    url: "/about"
  - title: "Build Log"
    url: "/categories/build-log/"
  - title: "Automation"
    url: "/categories/automation/"
  - title: "Tech Implementation"
    url: "/categories/tech-implementation/"
  - title: "Templates"
    url: "/categories/template-archive/"
  - title: "Career & Mentoring"
    url: "/categories/career-mentoring/"
  - title: "Talk & Teach"
    url: "/categories/talk-teach/"
  - title: "SumInsideTech"
    url: "/categories/suminsidetech/"
